apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  namespace: joaojunior
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: joaoesjunior/api-container:api-0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /home/joaojunior/project2-pv2
          name: project2-pv2-joaojunior
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: project2-pv2-joaojunior
        persistentVolumeClaim:
          claimName: project2-pvc-joaojunior
      restartPolicy: Always
