apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: joaojunior
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30502
  type: NodePort  

