apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-model-deployment
  namespace: joaojunior
spec:
  replicas: 1  # Apenas um pod de treinamento
  selector:
    matchLabels:
      app: train-model
  template:
    metadata:
      labels:
        app: train-model
    spec:
      containers:
      - name: train-model
        image: joaoesjunior/ml-container:ml-0.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/joaojunior/project2-pv2
          name: project2-pv2-joaojunior
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Always  # Reinicia o pod automaticamente em caso de falha
      volumes:
      - name: project2-pv2-joaojunior
        persistentVolumeClaim:
          claimName: project2-pvc-joaojunior
