apiVersion: batch/v1
kind: Job
metadata:
  name: train-model-job
  namespace: joaojunior
spec:
  template:
    spec:
      containers:
      - name: train-model
        image: joaoesjunior/ml-container:ml-0.1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/joaojunior/project2-pv2
          name: project2-pv2-joaojunior
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
      volumes:
      - name: project2-pv2-joaojunior
        persistentVolumeClaim:
          claimName: project2-pvc-joaojunior
  backoffLimit: 0  # Define o número de tentativas de reinício (0 = nenhuma)
